version: "3.9"

services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: sqlserver
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=YourStrong!Passw0rd
      ports:
        - "1433:1433"
      volumes:
        - sqlserver_data:/var/opt/mssql
      networks:
        - backend

  walletservice.api:
    build:
      context: .
      dockerfile: WalletService/Api/WalletService.Api/Dockerfile
    container_name: walletservice
    depends_on:
        - sqlserver
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__Default=Server=sqlserver;Database=UserDataAccessServiceDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
        - "5001:5001"
    networks:
        - backend
    volumes:
        - ./UserDataService/Api/UserDataAccessService.Api/wwwroot/images:/app/wwwroot/images

volumes:
  sqlserver_data:

networks:
  backend:
    driver: bridge